yesiamrajeev/Hacktoberfest2025

- Java/array.java
finding a missing number in an array.
> missing number

- Python/Factorial.py
I have added another file demonstrating factorial of a number
> Created Factorial.py

- Python/Fibonacci.py
I have added Fibonacci.py file into python
> Created Fibonacci.py

- Python/Python.py
I have added a python file which demonstrates Fibonacci series
> Created Python.py

- Python/Python.py
Demonstration of basic data types in python
> Made changes in python.py file

- Python/Binarysearch.py
I have added a binary search program
> Created Binarysearch.py

- Python/Insertionsort.py
i have added insertion sort in python folder
> Created Insertionsort.py

- Python/Quiicksort.py
i have added quick sort into python folder
> Created Quiicksort.py

- Python/mergesort.py
i have added merge sort file into python folder
> Created mergesort.py

- Python/perfect_square.py
A basic program to check if the number entered by the user is a perfect square using loops.
> Checking for perfect square

- C++/reverse_queue.cpp
Added the code to reverse a queue using i) stack and ii) recursion
> Created reverse_queue.cpp

- C++/radixsort_algorithm.cpp
- README.md
Fixed some formatting issues in README.md File.
Added C++/radixsort_algori thm.cpp
Happy Hacketoberfest 2024
> Fixed README.md, Added C++/radixsort_algori thm.cpp

- Java/Heap.java
This PR adds a generic heap implementation that supports both Max-Heap and Min-Heap functionalities using Java. The class provides methods to insert elements, remove the root, and perform heap sorting. The code uses generic types to ensure flexibility for different data types that implement the Comparable interface. The implementation includes:
-  Max-Heap and Min-Heap insertions
-  Up-heap and down-heap operations to maintain heap properties
-  Heap sort for both heaps
> Added Generic Heap Implementation Supporting Max-Heap and Min-Heap

- Java/Sum of Array.java
Provided code is a basic solution in Java to find out sum of elements present in an Array .
> Create Sum of Array.java

- Python/food_fill.py
> Created food_fill.py

- Python/dijkstra.py
> Created dijkstra.py

- C++/astar_search_algorithm.cpp
Hello! I have added the Implementation of A* Search Algorithm. I hope it counts towards hacktoberfest2024.
Happy Hacking!!
> Implementation of A* Search Algorithm

- Python/is_prime.py
added a program to check whether a number is prime number or not
> Created is_prime.py

- Python/is_perfect_number.py
i have added a program to check whether a number is a perfect number or not
> Created is_perfect_number.py

- C++/PersonalFinanceManager.cpp
This pull request introduces a Personal Finance Management System implemented in C++. The application allows users to track their incomes, expenses, and savings while setting and monitoring financial goals. The code provides a user-friendly interface for managing finances and displaying comprehensive financial overviews, making it easier for users to gain insights into their financial health.
> Implement Personal Finance Management System in C++

- C++/Kruskal_algorithm.cpp
This PR adds an implementation of Kruskal's Algorithm to calculate the Minimum Spanning Tree (MST) for a given graph. The approach is designed to work with an edge list and makes use of Union-Find (Disjoint Set Union) to efficiently connect components.
> Added Kruskal_algorithm

- C++/Asteroid Collision
- C++/SpiralMatrix.cpp
implemented an efficient solution using a stack-based approach. The code handles the collision logic between asteroids moving in opposite directions, ensuring optimal time complexity while solving the problem accurately.
> Asteroid Collision Problem

- C++/Even_Numbers_hate.cpp
Added Even Numbers hate problem
> Added Even_Numbers_hate

- C++/Floyd_Warshall_algorithm.cpp
The Floyd-Warshall algorithm is a dynamic programming algorithm used to find the shortest paths between all pairs of vertices in a weighted graph. It works for both directed and undirected graphs and can handle negative weights, though it does not work with graphs containing negative weight cycles.
> Added Floyd_Warshall_algorithm

- Python/bubble_sort.py
i have added bubble sort algorithm
> Created bubble_sort.py

- C++/blood_bank_management_system.cpp
Created a Blood Bank Management System in C++ to manage blood donations and requests. Key features include adding/updating donors, viewing blood types, requesting blood, and searching for donors. The system uses a menu-driven interface for improved user interaction and employs a vector for dynamic storage, ensuring scalability and efficient data management. This project serves as a valuable tool for community health organizations and blood banks to track donations and manage inventory effectively.
> Implement Advanced Blood Bank Management System in C++

- Python/knap_sack.py
I have added knapsack algorithm
> Created knap_sack.py

- Python/Fibonacci Series using Memoization.py
This program of Fibonacci uses memoization in order to increase efficiency to calculate the number and produce faster results.
> Create Fibonacci Series using Memoization.py

- C++/countSort.cpp
Added count Sort code in CPP taking time complexity of O(n+k)
> added countSort code

- Python/Odd and Even Checker using Generators.py
I have created a program to check whether numbers are odd or even using the concept of generators in Python.
> Create Odd and Even Checker using Generators.py

- C++/KadaneAlgo.cpp
Added the code to find maximum subarray in an array.
> Added code for Kadane's Algorithm

- Java/BurstBalloons.java
Problem: You are given n balloons, each with a number of coins printed on it. You burst a balloon, you will get coins equal to the product of the coins of the balloons adjacent to it. Find the maximum coins you can collect by bursting the balloons wisely.
> Add code for  Burst Balloons problem

- Java/WordLadder.java
Problem: Given two words, beginWord and endWord, and a dictionary's word list, find the length of the shortest transformation sequence from beginWord to endWord, such that:
1.Only one letter can be changed at a time.
2.Each transformed word must exist in the word list.
> Create code for Word Ladder problem

- Java/TrappingRainWater.java
Problem: You are given n balloons, each with a number of coins printed on it. You burst a balloon, you will get coins equal to the product of the coins of the balloons adjacent to it. Find the maximum coins you can collect by bursting the balloons wisely.
> Create code for TrappingRainWater problem

- Python/Code to find Maximum sum of SubArray by Kadane's Algorithim.py
> Create Maximum sum of SubArray by Kadane's Algorithim.py

- Java/To Lower Case.java
This Program in Java demonstrates to Convert a String to its lowercase letters.
> Create To Lower Case.java

- Java/NumberScrambleGame.java
In this game, the player is presented with a scrambled sequence of numbers and has to rearrange them in the correct order in as few moves as possible. The player can only swap two numbers at a time.
1. The game scrambles the numbers 1-9 randomly.
2. The player is prompted to swap two positions in the array to attempt to reorder them in ascending order (1 through 9).
3. The game continues until the array is sorted, counting how many moves it takes the player to complete the game.
4. The player wins once the numbers are in the correct order.
> Create a Number Scramble Game in java

- Python/Tower_of_hanoi.py
I have added tower of hanoi algorithm
> Created Tower_of_hanoi.py

- Java/NaturalNumbersSum.java
Program in Java to Compute Sum of Natural Number till n Terms.
> NaturalNumbersSum.java

- C++/Mergesort.cpp
Merge Sort is a recursive sorting algorithm based on the divide-and-conquer approach. The array is divided into two halves, and these halves are recursively sorted. The mergeSort() function splits the array, and the merge() function combines two sorted subarrays back into one. It operates in O(n log n) time complexity, making it efficient for large datasets. This code takes input for the size and elements of the array from the user, sorts the array using merge sort, and then prints the sorted array. The merge process ensures the subarrays are combined in sorted order.
> Created a merge sort code 

- Java/TopoSort using dfs.java
> Create TopoSort using dfs.java

- C++/StrongPasswordChecker.cpp
A password is considered strong if the below conditions are all met:
It has at least 6 characters and at most 20 characters.
It contains at least one lowercase letter, at least one uppercase letter, and at least one digit.
It does not contain three repeating characters in a row (i.e., "Baaabb0" is weak, but "Baaba0" is strong).
Given a string password, return the minimum number of steps required to make password strong. if password is already strong, return 0.
In one step, you can:
Insert one character to password,
Delete one character from password, or
Replace one character of password with another character.
> A strong password checker

- C++/Insertion_Sort.cpp
Added Insertion Sort Algorithm that inserts an element to a part of the array that is sorted. 
#97 Insertion Sort Algorithm in C++
Code is complete with comments and follows OOPs.
Also,it can take inputs from user and return an output.
> Added Insertion_Sort.cpp

- C++/burning-tree.cpp
> burning tree

- C++/heapsort.cpp
this is a min-heap algorithm which consist of heapify function,
Comments are added for each function in the program for better understanding.
> Added a sorting algorithm called Heap Sort

- C++/palindrome_substring_problem.cpp
Palindrome substring problem in c++ language added
> Palindrome substring Problem

- C++/Skewd.cpp
##Overview
This C++ code implements a binary search tree (BST) with insertion . It inserts nodes based on their values, maintaining the BST property (left child is smaller, right child is larger). The code checks if the tree is skewed, meaning all nodes are either aligned to the left or the right, and prints whether the tree is skewed or not.
##Issue Addressed
#106
> Added file for Skewed BST

- C++/ConnectedGraph.cpp
This code finds out if a given graph is a Connected graph or not. It traverses the graph by BFS traversal. If any node is not visited, it is kept false and marked true if it is visited. If at the end, a node is not visited then it is not a connected graph
#103 
- The code is properly commented at required places. 
- The code can take inputs from user and provide with the correct output.
> Created ConnectedGraph.cpp

- C++/longest_substring.cpp
added problem to find  longest substring without repeating character.please assign it to me.
>  Longest substring without repeating character

- CONTRIBUTING.md
Added `CONTRIBUTING.md` file as requested. This document outlines:
Issue reporting guidelines
Pull request submission process
Coding standards
Purpose: Improve documentation, foster community engagement, and streamline contributions.
Part of the **Hacktoberfest** initiative, approved by the maintainer. Helps meet participation criteria by providing clear contribution guidelines.
This PR is for issue number #101, Review contents to ensure alignment with project needs. Thank you for considering this contribution!
> Add CONTRIBUTING.md for Hacktoberfest

- C++/Asteroid Collision.cpp
- C++/rotten_oranges.cpp
Also renamed a file of Asteriod Collision  with .cpp extension 
added the required libraries for the asteroid collision code
> Added Rotten oranges problem and added dot extension to the existing file.

- Python/TSP.py
##Overview
This code implements a solution for the Traveling Salesman Problem (TSP) using a dynamic programming approach with memoization. It defines a function TSP that takes a distance matrix as input, representing the distances between cities. The function recursively explores all possible routes starting from the first city, calculating the minimum cost to visit all cities and return to the starting point. The results are stored in a memoization table.
##Issue Addressed
#123
> Added code file for TSP 

- Python/Anagram_checker.py
i have added anagram checker program into python dir
> Created Anagram_checker.py

- Python/LongestRepeatingCharacterReplacement.py
@yesiamrajeev could you please check my contribution, Happy Hacktoberfest-2024
> added LongestRepeatingCharacterReplacement.py

- Java/matrix.java
Program to display the transpose of a matrix.
> Created a matrix program.

- Java/Banking System.java
> Create Banking System.java

- C++/Trees/Validate Binary Search Tree.cpp
> Create Validate Binary Search Tree.cpp

- C++/Trees/KthLargestSum_in_BT.cpp
Added Binary Tree problem: Kth Largest Sum in a Binary Tree in C++.
> Add Kth Largest Sum in a Binary Tree

- C++/Subset.cpp
Hey @yesiamrajeev 
Added Subset Algorithm
>  Add Subset algorithm in C++

- Java/Dijkstra's Algorithm.java
>  Dijkstra's Algorithm.java

- Python/LRU Cache.py
> Create LRU Cache.py

- C/merge_Sort.c
Created a .c file for implementation of Merge Sort in C language.
> Added C code for Merge Sort

- C/merge_Sort.c
- C/selection_Sort.c
Create a .c file for implementation of Selection Sort in C language.
> Branchdsa2

- C/insertion_Sort.c
Created a C file to add implementation of Insertion Sort in C language.
> Added C code for Insertion Sort

- C/insertion_Sort.c
- C/stack.c
Created a C file to demonstrate implementation of Stack operations in C language. It is a menu-driven program.
> Branchdsa4

- C/insertion_Sort.c
- C/queue.c
- C/stack.c
Created a C file to demonstrate the implementation of Queue operations in C language. It is a menu-driven program.
> Branchdsa5

- C++/Count Odd Numbers in an Interval Range.cpp
This will close #152 
1523. 
Count Odd Numbers in an Interval Range
Given two non - negative integers low and high. Return the count of odd numbers between low and high(inclusive).
Example 1:
Input: low = 3, high = 7
Output : 3
Explanation : The odd numbers between 3 and 7 are[3, 5, 7].
Example 2 :
Please add Hacktoberfest labels to this PR.
> Add: Count Odd Numbers in an Interval Range

- C++/moore's voting algo.cpp
Adding Moore's Voting Algorithm
Question:
Given an array of n integers, find the majority element, 
which is defined as the element that appears more than n/2 times in the array. 
If no such element exists, return -1.
Hi @yesiamrajeev Can you please add labels for hacktoberfest
Thank you
> moores voting algorithm 

- Java/PalindromeNumber.java
I created a palindrome number checker in Java. A palindrome reads the same backward and forward, like 121. To ensure it’s efficient and accurate, I tested it on LeetCode, and it passed all the cases! This project helped me sharpen my skills with algorithms. Check out the code if you’re interested!
Time Complexity: O(*n*)
> Added Palindrome number checker in java #151

- C++/mos_algorithm_offline_queries.cpp
> add: mos algorithm for offline queries issue id #162

- Python/FlipEquivalentBinaryTrees.py
Hey @yesiamrajeev
The program will print True if the two trees are flip equivalent, otherwise False.
This solution efficiently checks the flip equivalence of two binary trees using a recursive approach. If you have any further questions or need additional modifications, feel free to ask!
> #128 Done Flip equivalent Binary trees in python

- Java/Binary_Search/Findfirstandlast.java
- Java/Binary_Search/Specialarray.java
- Java/Binary_Search/findPeakElement.java
- Java/Binary_Search/kokoEatingBanana.java
- Java/Binary_Search/searchInRotetedArray.java
I added standard problems on binary search from LeetCode:-
- Find First and Last Position: This problem helps us understand how to efficiently locate the boundaries of a target value in a sorted array.
- Find Peak Element: This challenge teaches us how to identify a peak in an array using binary search techniques.
- Special Array: This problem encourages us to apply binary search in a unique context to determine special conditions in an array.
These problems are great for honing our understanding of binary search and its applications.
> Adding bs folder

- Java/HollowDiamond.java
Pattern for Hollow Diamond in Java
issue fixes #181
> Hollow Diamond in java

- Leetcode_Questions/Strings/question.md
Hi,
I have added list of five important leetcode string questions that may help in improving others in coding. 
Please label this pull request under Hacktoberfest 2024.
Thank you
> Leetcode String Questions

- Palindrome number
Simple code for palindrome numbers in java language.
> Palindrome number

- C++/Binary Search Tree/KthElementinBinarySearch.cpp
Added code for finding finding kth smallest/largest element in Binary Search Tree.
Please merge this pull request with labels : hacktoberfest2024, hacktoberfest-accepted.
> Solved issue #192 Added code for finding kth smallest/largest element in BST

- C++/Dynanic Programming/UnbondedKnapsack.cpp
I have solved issue #196 .
please check and merge this pull request with label hacktoberfest2024-accepted.
> Solved issue #196.

- C++/Binary_search.cpp
This C++ program implements the Binary Search algorithm, which efficiently searches for a target value in a sorted array. The program takes a sorted array and a target value as input, and it returns the index of the target if found, or -1 if the target is not present in the array. The algorithm operates with a time complexity of O(log n), making it suitable for large datasets. This implementation demonstrates how to use iterative binary search to locate elements efficiently.
Example Usage:
Input: arr = [1, 2, 3, 4, 5, 6, 7], target = 5
Output: Element found at index: 4
> Add binary_search.cpp: Implement binary search algorithm

- Removed duplicates from sorted array
Using simple ArrayList concept this programme removes duplicates from an array
> Removed duplicates from sorted array

- C++/Remove Duplicates from Sorted List.cpp
Closes issue #200 
Problem Statement:
Given the head of a sorted linked list, delete all duplicates such that each element appears only once.
Return the linked list sorted as well.
Example:
Input: head = [1,1,2]
Output: [1,2]
> Add : Remove Duplicates from Sorted List

- Java/MergeArray.java
> MergeArray.java

- C/xor_cipher.c
> Added XOR Cipher Algorithm

- C++/TernarySearch.cpp/CountInvUsingMergeSort.cpp
- C++/TernarySearch.cpp/MinRange.cpp
- C++/TernarySearch.cpp/findPeak.cpp
- C++/TernarySearch.cpp/intro.cpp
- C++/TernarySearch.cpp/limitations.cpp
- C++/TernarySearch.cpp/parabolicCurve.cpp
- C++/TernarySearch.cpp/peakInRotatedArray.cpp
Add Algorithms to ternary search in c++ folder
- CountInvUsingMergeSort
- findPeak
- intro
- limitations
- MinRange
- parabolicCurve
- peakInRotatedArray
> Add Ternary search algorithms to C++ folder

- SQL/Top Earners.sql
I have added my code here please accept it as a contribution
> Create Top Earners.sql

- C++/Greedy Algorithms/Fractinal Knapsack.cpp
Add Fractional Knapsack Algorithm in greedy algorithms section in c++
> Add fractional Knapsack Algorithm in greedy Algorithms in C++

- C++/Backtracking/NqueensSolution.cpp
I have added the solution for the issue #239 Nqueens puzzle using backtracking approach in cpp
i have created a separate folder for backtracking and included the solution there
the solution has passed all the test cases of leetcode
> added nqueens problem solution using backtracking in cpp

- C++/Dynanic Programming/LongestCommonSuqsequence2.cpp
> Add LongestCommonSubsequence problem Dynamic Programmming folder in  c++

- C++/Dynanic Programming/NthStair.cpp
> Add Nth stair algorithm in dynamic programming folder in C++

- BinaryToDecimal.cpp
- C++/Dynanic Programming/FloydWarshallAlgo.cpp
This PR solves the issue #265 I have implemented the  solution using cpp with time complexity of 0(n)
Dear Maintainers
please add the respected labels 
@yesiamrajeev
> Added the Solution for Binary to Decimal problem

- C++/Dynanic Programming/FloydWarshallAlgo.cpp
This pr solves the issue #248 I have implemented the Algorithm of Floyd Warshall using DP and in cpp 
Dear Maintainers,
Please add the required labels for hacktoberfest
> added the floyd warshall algo to DP

- Leetcode_Questions/arrays/2149_rearrange_array_by_sign.py
Closes #256
Added Python solution for LeetCode 2149: Rearrange Array Elements by Sign
under Leetcode_Questions/arrays/.
Author: Daddy-Myth
> Added Python solution for Leetcode 2149 in arrays folder

- Sieve-Algorithm.java
Here is simply and unique Sieve algorithm i created hope 🙏 it's fine ... A small contribution 😁
@yesiamrajeev
> Sieve-Algorithm.java

- Java/EditDistance.java
Given two strings, find the minimum number of operations required to convert one string into the other.  
**Allowed operations:**
- Insertion
- Deletion
- Replacement
> Added EditDistance.java implementation

- ColorGuessingGame/index.html
- ColorGuessingGame/script.js
- ColorGuessingGame/style.css
Added a fun, interactive Color Guessing Game using HTML, CSS, and JavaScript. 
**Features:**
- Displays a random RGB color value.
- Users select the correct color from three options.
- Provides instant feedback: "Correct!" or "Wrong! Try again".
- Includes a "Play Again" button to reset the game.
- Fully responsive and works in any modern browser.
This contribution is part of Hacktoberfest 2025.
> Add Color Guessing Game (HTML, CSS, JS)

- Tortoise-Hare-Applications/LinkedListCycle.java
- Tortoise-Hare-Applications/LinkedListMiddle.java
- Tortoise-Hare-Applications/Node.java
- Tortoise-Hare-Applications/RemovingNthNodeFromBack.java
PR Title: Add Slow & Fast Pointer Examples for Linked Lists
PR Description:
Closes #224 
Description 📝
This pull request introduces three classic linked list algorithms, all implemented in Java using the Slow and Fast Pointer (also known as the Tortoise and Hare) technique.
As discussed in the issue, these examples are fundamental for understanding linked list manipulations and are frequently asked in technical interviews. 
What's New? 🚀
✅ Well-Commented Code: Each implementation includes detailed comments explaining the logic, pointer movements, and edge cases.
> Added implementation using slow-fast pointer

- Java/TortoiseAndHare.java
This pull request introduces an implementation of the **Tortoise and Hare (Slow and Fast Pointer)** algorithm in Java. The solution efficiently determines whether a **cycle exists in a singly linked list** using two pointers moving at different speeds.
- Added a new Java class implementing the Tortoise and Hare algorithm.
- Detects the presence of a cycle in a linked list in **O(n)** time and **O(1)** space.
- Returns `true` if a cycle is present, `false` otherwise.
Detecting cycles is a fundamental operation in linked list problems. The **Tortoise and Hare** algorithm is both time-efficient and memory-efficient, avoiding the need for extra data structures while ensuring accurate results.
- ✅ Linked list **with a cycle** → correctly returns `true`.
- ✅ Linked list **without a cycle** → …
> Implement Tortoise and Hare Algorithm to Detect Cycle in Linked List

- Leetcode_Questions/javaSol/Solution(atio).java
This file provides the fix for issue #202  by implementing a solution to the LeetCode problem "String to Integer (atoi)".
The approach runs in O(n) time complexity, ensuring efficiency while correctly handling edge cases such as whitespace, signs, and integer overflow.
Also, since this is part of Hacktoberfest, I’d really appreciate it if you could label this PR as hacktoberfest-accepted 🙌
> added stoi problem solution LC-8
